### ISSUE TITLE
[Steam] error clicking cookie

### ISSUE THREAD

**Issue by uecasm** [prinzstani/CookieBot#69] opened 2021-09-04 00:53 UTC
FYI, when loading this in the Steam version, the following error occurs:
```
Uncaught TypeError: Cannot read property 'detail' of undefined
    at Object.Game.ClickCookie (main.js?v=2.089:4634)
    at Object.AutoPlay.handleClicking (cookieAutoPlayBeta.js:254)
    at AutoPlay.run (cookieAutoPlayBeta.js:64)
```

**Comment by pie3636** [comment] 2021-09-05 16:31
The issue is quite possibly related to these changes in the Steam version:
https://github.com/CookieMonsterTeam/CookieMonster/issues/950#issuecomment-911998336

**Comment by pie3636** [comment] 2021-10-30 09:55
@uecasm Does the error still show up for you? I just loaded the latest version of the game with the add-on, and I'm not seeing any error messages. The big cookie clicking also seems to work just fine.
If you do still get the error, could you also point out how to open the console to actually see the logs?

**Comment by Kikithecat12345** [comment] 2022-03-29 19:30
@uecasm If the bug is fixed for you, let us know so we can close the issue.

**Comment by Kikithecat12345** [comment] 2024-12-08 21:36
Closing due to inactivity. @uecasm, if this issue is still happening, feel free to reopen.

**Closed as not planned by Kikithecat12345** 2024-12-08 21:36 UTC
Labels: bug, good first issue

**Comment by Kikithecat12345** [comment] 2024-12-08 21:37
(oops, wrong closed)
